# path to samplesheet
samplesheet: samples.csv

wdl: /home/rmmeyers/workflows/atac-seq-pipeline/atac.wdl

caper_options: ""

template_json: sample_template.json

fastq_dirs:
  - '/home/rmmeyers/workflows/atac-encode-snakemake/.test/fastqs/'

make_consensus: True

# grouping_columns:
#   - Timepoint

max_group_align_size: 200000000

# % will be replaced with the character '1' and '2' for reads 1 and 2 respectively
fastq_suffix: _*R%*.fastq.gz

local_main_job: False
use_tmpdir: False

genome_fasta: /oak/stanford/groups/khavari/users/rmmeyers/genomes/Homo_sapiens/hg38_atac/GRCh38_no_alt_analysis_set_GCA_000001405.15.fasta
chrom_sizes: /oak/stanford/groups/khavari/users/rmmeyers/genomes/Homo_sapiens/hg38_atac/GRCh38_EBV.chrom.sizes.tsv
