# path to samplesheet
samplesheet: samples.csv

wdl: /home/rmmeyers/workflows/atac-seq-pipeline/atac.wdl

template_json: sample_template.json

fastq_dirs:
  - '/home/rmmeyers/workflows/atac-encode-snakemake/.test/fastqs/'
