name: atac-encode-snakemake
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - snakemake
  - samtools
  - biopython
  - numpy
  - pandas
  - openjdk
  - pip
  - pip:
    - caper
    - croo
    - qc2tsv