$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake configuration file

type: object

properties:
  samplesheet:
    type: string

  wdl:
    type: string

  template_json:
    type: string

  fastq_dirs:
    type: array

  fastq_suffix:
    type: string

            
required:
  - samplesheet
  - wdl
  - template_json
  - fastq_dirs
  - fastq_suffix
  